name: Build and deploy the landing page

on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Azure Static Web Apps Deploy'
      uses: Azure/static-web-apps-deploy@v1
      with:
        action: 'upload'
        app_location: 'my-app'
        azure_static_web_apps_api_token: ${{ secrets.AZURE_LANDING_DEPLOY_TOKEN }}
        #api_build_command: # optional
        #api_location: # optional
        #app_artifact_location: # optional
        output_location: 'dist'
        #app_build_command: # optional
        #repo_token: # optional
        #routes_location: # optional
        #skip_app_build: true
